params:
  training_experiment: baselines.train_iforest
  validation_metric: best_ts_f1_score
  evaluation_metrics:
    - best_ts_f1_score
    - ts_auprc
    - best_ts_f1_score_classic
    - ts_auprc_unweighted
    - best_f1_score
    - auprc
dataset:
  name: SMDDataset
training_param_updates:
  dataset:
    name: SMDDataset
  training:
    epochs: 1
detector_param_grid:
  dataset:
    pipeline:
      window:
        args:
          window_size:
            - 5
            - 10
            - 20
          step_size:
            - 1
            - 5
  detector_params:
    n_trees:
      - 100
      - 200
      - 500
    max_samples:
      - null
      - 0.2
      - 0.5
    # max_features:
    #   - 1.
    #   - 0.8
    # bootstrap:
    #   - False
    #   - True
