params:
  training_experiment: baselines.train_eif
  validation_metric: best_ts_f1_score
  evaluation_metrics:
    - best_ts_f1_score
    - ts_auprc
    - best_ts_f1_score_classic
    - ts_auprc_unweighted
    - best_f1_score
    - auprc
dataset:
  name: SMDDataset
training_param_updates:
  dataset:
    name: SMDDataset
  training:
    epochs: 1
detector_param_grid:
  dataset:
    pipeline:
      window:
        args:
          window_size:
            - 5
            - 10
            - 20
          step_size:
            - 1
            - 5
  detector_params:
    n_trees:
      - 350
      - 500
    sample_size:
      - 256
      - 512
    extension_level:
      - null
      - 10
